#!/bin/bash
# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

loxberryhome=REPLACEINSTALLFOLDER
pluginname=REPLACEFOLDERNAME
pluginbindir=REPLACELBPBINDIR

# Directory/Pluginname fallback for test environment
if [ ! -d $loxberryhome ]; then
	loxberryhome=/opt/loxberry
fi
if [ ! -d $pluginname ]; then
	pluginname=tcp2udp
fi
if [ ! -d $pluginbindir ]; then
	pluginname=/opt/loxberry/bin/plugins/tcp2udp
fi

# Starting TCP2UDP-Control
$pluginbindir/tcp2udp-control.pl &

exit 0
